### PR TITLE
[exporter/datasetexporter]: Call the currect function on shutdown

### PR DESCRIPTION
**Pull request by martin-majlis-s1**
**Description:** When exporter is shutting down, we have to call the correct shutdown function.

We have introduced new function that should be called during the shutdown but we haven't updated the datasetexporter code.

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24253

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>
see also https://github.com/scalyr/dataset-go/pull/30/files

### CODE REVIEW

**Review by tomaz-s1 — APPROVED** [review]
LGTM 👍 

Do we have corresponding end to end tests for that / we plan to add it now, have a separate JIRA ticket for it or similar?

**Comment by martin-majlis-s1** [comment]
This is the following task - https://sentinelone.atlassian.net/browse/DSET-4050 and I am planning to verify it. For now I do not know, how to verify it, that it's work as expected, that would really convince me. So I will do some best effort.

**Comment by tomaz-s1** [comment]
@martin-majlis-s1 One easy quick manual way could be to test it with the helm chart / Kubernetes.

Create new helm chart deployment, send some data, stop sending data, run helm upgrade to upgrade the app. 

This will result in new app roll out (old pod will be and new one created). If the change is working correctly, old pod should stop fast (since no data is flowing in) and Kubernetes shouldn't need wait up to 60 seconds / configured grace period before killing the pod.

Keep in mind though that this only covers simple "no data is flowing in" path. It would still be nice to also test data is flowing in and new data is being rejected flow.

**Comment by tomaz-s1** [comment]
I actually assume you wanted to create this branch against ``datasetexporter-latest`` branch and not the ``main`` one, or?

**Pull request merged**
